routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'clients');
Route::resource('clients', 'ClientController', ['only' => ['index', 'store', 'destroy']]);

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\ClientService;

class ClientController extends Controller
{
    private $client_service;

    public function __construct(ClientService $client_service)
    {
        $this->client_service = $client_service;
    }

    public function index()
    {
        $clients = $this->client_service->getAllClients();

        if (request()->has('export')) {
            return $this->client_service->downloadClientsCSV();
        }

        return view('clients.index')->withClients($clients);
    }

    public function store(Request $request)
    {
        $this->client_service->importClientsByCSV($request->get('csv'));

        return response()->json(array());
    }

    public function destroy($id)
    {
        $this->client_service->destroyClient($id);

        return back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/clients/index.blade.php
@extends('layouts.master') @section('content')
<div class="mt-5"></div>

<div class="container-fluid">
    <div class="row">
        <div class="col-12 title">
            <h1>Clientes</h1>
        </div>
    </div>

    <div class="my-4"></div>

    <div class="row">
        <div class="col-12 d-flex justify-content-end">
            <div class="row">
                <div class="col-12 d-flex justify-content-end">
                    <button class="btn btn-file icon mr-2">
                        <input type="file" class="custom-file-input" id="csv">
                        <i class="fa fa-upload"></i>
                        Importar CSV
                    </button>
                    <a class="btn btn-line icon" href="{{ route('clients.index', ['export']) }}">
                        <i class="fa fa-download"></i>
                        Exportar CSV
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="fazendo-upload" style="display: none">
        <div class="col-12">
            <div class="mt-3"></div>

            <div class="alert alert-info">
                Fazendo o Upload do Arquivo
            </div>
        </div>
    </div>

    <div class="row" id="concluido-upload" style="display: none">
        <div class="col-12">
            <div class="mt-3"></div>

            <div class="alert alert-success">

            </div>
        </div>
    </div>

    <div class="mt-3"></div>

    <div class="row">
        <div class="col-12">
            <table class="table table-hover tabela-padrao">
                <thead>
                    <tr>
                        <th scope="col">Nome</th>
                        <th scope="col">Email</th>
                        <th scope="col">Data de Nascimento</th>
                        <th scope="col">CPF</th>
                        <th scope="col">Endereço</th>
                        <th scope="col">CEP</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($clients as $client)
                    <tr>
                        <td>{{ $client->nome }}</td>
                        <td>{{ $client->email }}</td>
                        <td>{{ $client->data_nascimento->format('d/m/Y') }}</td>
                        <td>{{ mask($client->cpf, '###.###.###-##') }}</td>
                        <td>{{ $client->endereco }}</td>
                        <td>{{ mask($client->cep, '#####-###') }}</td>
                        <td style="padding: 0">
                            <form action="{{ route('clients.destroy', $client->id) }}" method="POST" onsubmit="return confirm('Deseja remover este cliente?');">
                                @csrf @method('DELETE')

                                <button class="btn btn-link icon">
                                    <i class="fa fa-trash"></i> Excluir
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection @push('body_scripts')
<script>
    $(document).ready(function() {
        $('#csv').on('change', function() {
            let $formData = new FormData();

            $formData.append('csv', $(this).get(0).files[0]);
            $('#fazendo-upload').toggle();

            axios.post('/clients', $formData).then(res => res.data).then(res => {
                $('#fazendo-upload').toggle();

                let $length = res.length;
                let $count = 3;

                $('#concluido-upload').find('.alert').html('Importação realizada');
                $('#concluido-upload').toggle();


                setInterval(function() {
                    if ($count > 0) {
                        $('#concluido-upload').find('.alert').html('Importação realizada.<br>Redirecionando em ' + $count +
                            ' ...');
                    } else {
                        location.reload();
                    }

                    $count--;
                }, 1000);
            });
        });
    });
</script>
@endpush

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>@yield('title', "Gerenciador de CSV's")</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- CSS -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <style>
            .btn {
                width: auto;
                height: auto;
                min-height: 40px;
                font-size: 14px;
                color: #FFF;
                padding: 5px 15px;
                border: 2px solid transparent;
                outline: 0;
                border-radius: 4px;
                -webkit-border-radius: 4px;
                -moz-border-radius: 4px;
                -o-border-radius: 4px;
                transition: all .4s ease-in-out;
                -moz-transition: all .4s ease-in-out;
                -webkit-transition: all .4s ease-in-out;
                -o-transition: all .4s ease-in-out;
                background-color: #46C364;
            }

            .title h1 {
                margin-bottom: 10px;
                padding-right: 20px;
                font-weight: 700;
                font-size: 2.5em;
                color: #0091e5;
            }

            .btn,
            .btn-link,
            strong {
                font-weight: 700;
            }

            .btn.active,
            .btn.focus,
            .btn:active,
            .btn:focus,
            .btn:hover {
                color: #FFF;
                outline: 0;
                background-color: #3DA856;
                border-color: #3DA856;
            }

            .btn-line {
                color: #4A4A4A;
                background: 0 0;
                border-color: #4A4A4A;
            }

            .btn-line:active,
            .btn-line:focus,
            .btn-line:hover {
                background: #0091e5;
                border-color: #0091e5;
                color: #FFF;
            }

            .btn-link {
                background: transparent;
                font-size: 14px;
                line-height: 1em;
                color: #4A4A4A;
                padding: 0;
                margin: 0;
            }

            .btn-link:active,
            .btn-link:focus,
            .btn-link:hover {
                background: transparent;
                border-color: transparent;
                color: #000;
            }

            .btn-file {
                position: relative;
                overflow: hidden;
            }

            .btn-file input {
                position: absolute;
                top: 0;
                right: 0;
                min-width: 100%;
                min-height: 100%;
                font-size: 100px;
                text-align: right;
                filter: alpha(opacity=0);
                opacity: 0;
                outline: none;
                background: white;
                cursor: inherit;
                display: block;
            }

            table td[class*=col-],
            table th[class*=col-] {
                position: static;
                display: table-cell;
                float: none;
            }

            .tabela-padrao {
                background-color: #FFF;
                margin: 0 0 20px;
                width: 100%;
            }

            .tabela-padrao td,
            .tabela-padrao th,
            .tabela-padrao tr {
                padding: 10px 15px;
            }

            .tabela-padrao th {
                background-color: #0091e5;
                font-size: 16px;
                font-weight: 600;
                height: 35px;
            }

            .tabela-padrao tr {
                border: 1px solid #E5E5E5;
            }

            .tabela-padrao td {
                color: #4A4A4A;
                font-size: 14px;
                font-weight: 400;
            }

            .tabela-padrao th,
            .tabela-padrao th .btn-link {
                text-transform: none;
                color: #FFF;
            }

            .tabela-padrao tr td .btn-link {
                display: inline-block;
                padding: 5px 0;
                font-size: 16px;
                color: #0091e5;
                font-weight: 700;
            }

            .icon .fa {
                margin-right: 7px;
            }
        </style>

        @stack('head_scripts')
    </head>

    <body>
        @yield('content')

        <!-- JavaScript -->
        <script src="{{ asset('js/app.js') }}"></script>

        @stack('body_scripts')
    </body>

</html>